/-
Copyright (c) 2026 Mathlib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matthew Robert Ballard
-/
module

public import Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Basic
public import Mathlib.RingTheory.MvPolynomial.Homogeneous
public import Mathlib.RingTheory.MvPolynomial.Ideal

/-!
# Projective Space as Proj of the Polynomial Ring

This file defines projective n-space over a commutative ring `R` as
`Proj(R[x₀, ..., xₙ])` using the standard grading by total degree.

## Main definitions

* `AlgebraicGeometry.Proj.mvPolynomialGrading`: The grading of `MvPolynomial (Fin (n+1)) R`
  by total degree, as a local instance.
* `AlgebraicGeometry.Proj.polynomialProj`: Projective n-space `Proj(R[x₀,...,xₙ])` as a scheme.
* `AlgebraicGeometry.Proj.coordinateBasicOpen`: The standard basic open sets `D₊(xᵢ)`.
* `AlgebraicGeometry.Proj.standardCover`: The standard affine open cover by
  `D₊(x₀), ..., D₊(xₙ)`.

## Implementation notes

Kenny Lau's PR #26061 defines the "official" projective space as `ℙ(n; S) := S × Proj ℤ[n]`
following the `AffineSpace` pattern. The definition here, `Proj(R[x₀,...,xₙ])`, is a necessary
building block for the isomorphism `ℙ(n; Spec R) ≅ Proj(R[n])` and suffices for Serre's theorem
on cohomology of line bundles.

## References

* [Stacks Project, Cohomology of projective space](https://stacks.math.columbia.edu/tag/01XS)
-/

@[expose] public section

set_option backward.isDefEq.respectTransparency false

noncomputable section

open MvPolynomial

namespace AlgebraicGeometry.Proj

variable (n : ℕ) (R : Type*) [CommRing R]

section Grading

/-- The standard grading of `MvPolynomial (Fin (n+1)) R` by total degree. -/
abbrev mvPolynomialGrading :
    GradedAlgebra (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R) :=
  MvPolynomial.gradedAlgebra

attribute [local instance] mvPolynomialGrading

/-- The coordinate variable `xᵢ` in `R[x₀,...,xₙ]`. -/
abbrev coord (i : Fin (n + 1)) : MvPolynomial (Fin (n + 1)) R := MvPolynomial.X i

theorem coord_mem_homogeneousSubmodule (i : Fin (n + 1)) :
    coord n R i ∈ MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R 1 :=
  MvPolynomial.isHomogeneous_X (R := R) i

end Grading

section Scheme

attribute [local instance] mvPolynomialGrading

/-- Projective n-space over `R`, defined as `Proj(R[x₀,...,xₙ])` with the standard grading. -/
def polynomialProj : Scheme :=
  AlgebraicGeometry.Proj (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R)

/-- The basic open set `D₊(xᵢ)` in projective n-space. -/
def coordinateBasicOpen (i : Fin (n + 1)) : (polynomialProj n R).Opens :=
  Proj.basicOpen (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R) (MvPolynomial.X i)

/-- The coordinate variables `xᵢ` are homogeneous of positive degree (degree 1). -/
theorem coord_homogeneous_pos (i : Fin (n + 1)) :
    coord n R i ∈ MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R 1 ∧ (0 : ℕ) < 1 :=
  ⟨coord_mem_homogeneousSubmodule n R i, Nat.one_pos⟩

end Scheme

section Cover

attribute [local instance] mvPolynomialGrading

/-- The coordinate variables span the irrelevant ideal of `R[x₀,...,xₙ]`:
every element of positive degree is in the ideal generated by `x₀, ..., xₙ`. -/
theorem irrelevant_le_span_coord :
    (HomogeneousIdeal.irrelevant
      (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R)).toIdeal ≤
    Ideal.span (Set.range (fun i : Fin (n + 1) => MvPolynomial.X (R := R) i)) := by
  intro x hx
  rw [HomogeneousIdeal.toIdeal_irrelevant, RingHom.mem_ker,
    GradedRing.projZeroRingHom_apply] at hx
  -- hx : ↑(DirectSum.decompose ... x 0) = 0
  -- This means the degree-0 component of x is 0
  rw [show Set.range (fun i : Fin (n + 1) => MvPolynomial.X (R := R) i) =
    MvPolynomial.X '' (Set.univ : Set (Fin (n + 1))) from (Set.image_univ (f := _)).symm]
  rw [MvPolynomial.mem_ideal_span_X_image]
  intro m hm
  simp only [Set.mem_univ, true_and]
  -- Need: ∃ i, m i ≠ 0, i.e., m ≠ 0
  -- We know 0 ∉ x.support because coeff 0 x = 0 (from hx)
  by_contra h
  push_neg at h
  have hm0 : m = 0 := Finsupp.ext (fun i => h i)
  subst hm0
  have h0 : MvPolynomial.homogeneousComponent 0 x = 0 := by
    rw [← MvPolynomial.decomposition.decompose'_apply (σ := Fin (n + 1)) (R := R) x 0]
    exact_mod_cast hx
  rw [MvPolynomial.homogeneousComponent_zero] at h0
  have hcoeff : MvPolynomial.coeff 0 x = 0 :=
    MvPolynomial.C_injective _ _ (h0.trans MvPolynomial.C_0.symm)
  simp only [MvPolynomial.mem_support_iff] at hm
  exact hm hcoeff

/-- The standard affine cover of `Proj(R[x₀,...,xₙ])` by the `D₊(xᵢ)`. -/
theorem iSup_coordinateBasicOpen_eq_top :
    ⨆ i : Fin (n + 1), coordinateBasicOpen n R i = ⊤ := by
  exact Proj.iSup_basicOpen_eq_top _ _ (irrelevant_le_span_coord n R)

/-- The standard affine open cover of projective n-space. -/
def standardCover :
    (polynomialProj n R).AffineOpenCover :=
  Proj.openCoverOfISupEqTop
    (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R)
    (fun i : Fin (n + 1) => MvPolynomial.X i)
    (fun i => coord_mem_homogeneousSubmodule n R i)
    (fun _ => Nat.one_pos)
    (irrelevant_le_span_coord n R)

end Cover

section CoordinateProduct

attribute [local instance] mvPolynomialGrading

/-- The product of coordinate variables indexed by a finset. -/
def coordProd (S : Finset (Fin (n + 1))) : MvPolynomial (Fin (n + 1)) R :=
  ∏ i ∈ S, coord n R i

@[simp]
theorem coordProd_empty : coordProd n R ∅ = 1 := by simp [coordProd]

@[simp]
theorem coordProd_singleton (i : Fin (n + 1)) :
    coordProd n R {i} = coord n R i := by simp [coordProd]

theorem coordProd_insert {S : Finset (Fin (n + 1))} {i : Fin (n + 1)} (hi : i ∉ S) :
    coordProd n R (insert i S) = coord n R i * coordProd n R S := by
  simp [coordProd, Finset.prod_insert hi]

theorem coordProd_mem_homogeneous (S : Finset (Fin (n + 1))) :
    coordProd n R S ∈
      MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R S.card := by
  unfold coordProd
  rw [show S.card = ∑ _ ∈ S, 1 from by simp]
  exact SetLike.prod_mem_graded
    (A := MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R)
    (fun _ => 1) (coord n R) fun k _ => coord_mem_homogeneousSubmodule n R k

theorem coordProd_eq_erase_mul (S : Finset (Fin (n + 1)))
    {j : Fin (n + 1)} (hj : j ∈ S) :
    coordProd n R S = coordProd n R (S.erase j) * coord n R j := by
  simp only [coordProd, ← Finset.mul_prod_erase S (coord n R) hj, mul_comm]

theorem coordinateBasicOpen_iInf (S : Finset (Fin (n + 1))) :
    ⨅ i ∈ S, coordinateBasicOpen n R i =
      Proj.basicOpen (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R)
        (coordProd n R S) :=
  (Proj.basicOpen_finset_prod _ S (coord n R)).symm

end CoordinateProduct

end AlgebraicGeometry.Proj
