/-
Copyright (c) 2026 Mathlib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Formalization
-/
import Mathlib.CategoryTheory.Triangulated.Deformation.Lemma77
import Mathlib.CategoryTheory.Triangulated.Deformation.HomVanishing

/-!
# Deformation of Stability Conditions — TStructure

Q(>t), Q(≤t), orthogonality, HN splitting, deformedSlicing
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits CategoryTheory.Pretriangulated
open scoped ZeroObject

universe v u

namespace CategoryTheory

/-! ### Extension closure (Bridgeland p.6) -/

/-- The extension-closed subcategory generated by an object property `P` (Bridgeland p.6).
An object `E` is in `P.ExtensionClosure` if it is zero, satisfies `P`, or is the middle
term of a distinguished triangle whose other two terms are in `P.ExtensionClosure`. -/
inductive ObjectProperty.ExtensionClosure {C : Type u} [Category.{v} C] [HasZeroObject C]
    [HasShift C ℤ] [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
    (P : ObjectProperty C) : ObjectProperty C where
  | zero {E : C} : IsZero E → P.ExtensionClosure E
  | mem {E : C} : P E → P.ExtensionClosure E
  | ext {X E Y : C} {f : X ⟶ E} {g : E ⟶ Y} {h : Y ⟶ X⟦(1 : ℤ)⟧} :
      Triangle.mk f g h ∈ distTriang C →
      P.ExtensionClosure X →
      P.ExtensionClosure Y →
      P.ExtensionClosure E

/-- Extension closure is monotone: if `P ≤ Q` then `P.ExtensionClosure ≤ Q.ExtensionClosure`. -/
theorem ObjectProperty.ExtensionClosure.mono {C : Type u} [Category.{v} C] [HasZeroObject C]
    [HasShift C ℤ] [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
    {P Q : ObjectProperty C} (h : P ≤ Q) :
    P.ExtensionClosure ≤ Q.ExtensionClosure := by
  intro E hE
  induction hE with
  | zero hZ => exact .zero hZ
  | mem hP => exact .mem (h _ hP)
  | ext hT _ _ ihX ihY => exact .ext hT ihX ihY

/-- If generators are orthogonal (`Hom(P, Q) = 0`), their extension closures are orthogonal.
Proof by nested induction on the `ExtensionClosure` structure, using the exact Hom sequences
from distinguished triangles. -/
theorem ObjectProperty.ExtensionClosure.hom_eq_zero {C : Type u} [Category.{v} C]
    [HasZeroObject C] [HasShift C ℤ] [Preadditive C]
    [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
    {P Q : ObjectProperty C}
    (h : ∀ (E F : C), P E → Q F → ∀ (f : E ⟶ F), f = 0)
    {E F : C} (hE : P.ExtensionClosure E) (hF : Q.ExtensionClosure F)
    (f : E ⟶ F) : f = 0 := by
  induction hE generalizing F with
  | zero hZ => exact hZ.eq_of_src f 0
  | mem hP =>
    induction hF with
    | zero hZ => exact hZ.eq_of_tgt f 0
    | mem hQ => exact h _ _ hP hQ f
    | ext hT _ _ ihA ihB =>
      obtain ⟨g, rfl⟩ := Triangle.coyoneda_exact₂ _ hT f (ihB _)
      simp [ihA g]
  | ext hT _ _ ihX ihY =>
    obtain ⟨g, rfl⟩ := Triangle.yoneda_exact₂ _ hT f (ihX hF _)
    simp [ihY hF g]

/-- Extension closure is closed under isomorphisms. -/
theorem ObjectProperty.ExtensionClosure.of_iso {C : Type u} [Category.{v} C] [HasZeroObject C]
    [HasShift C ℤ] [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
    {P : ObjectProperty C} {X Y : C} (e : X ≅ Y)
    (h : P.ExtensionClosure X) : P.ExtensionClosure Y := by
  obtain ⟨Z, g, k, hT⟩ := distinguished_cocone_triangle e.hom
  have hZ : IsZero Z := (Triangle.isZero₃_iff_isIso₁ _ hT).mpr
    (show IsIso (Triangle.mk e.hom g k).mor₁ from e.isIso_hom)
  exact .ext hT h (.zero hZ)

/-- Walking a Postnikov tower: if every factor satisfies `Q`, the total object is in
`Q.ExtensionClosure`. This is the bridge from HN-filtration data to extension-closure
membership. -/
theorem ObjectProperty.ExtensionClosure.of_postnikovTower {C : Type u} [Category.{v} C]
    [HasZeroObject C] [HasShift C ℤ] [Preadditive C]
    [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
    {Q : ObjectProperty C} {E : C} (P : Triangulated.PostnikovTower C E)
    (hfactors : ∀ i, Q (P.factor i)) : Q.ExtensionClosure E := by
  suffices h : ∀ k (hk : k ≤ P.n),
      Q.ExtensionClosure (P.chain.obj' k (by omega)) by
    exact .of_iso (Classical.choice P.top_iso) (h P.n le_rfl)
  intro k
  induction k with
  | zero =>
    intro _
    rw [show P.chain.obj' 0 (by omega) = P.chain.left from rfl]
    exact .zero P.base_isZero
  | succ k ih =>
    intro hk
    have hchain_k := ih (by omega)
    set T := P.triangle ⟨k, by omega⟩
    have hT := P.triangle_dist ⟨k, by omega⟩
    have e₁ := Classical.choice (P.triangle_obj₁ ⟨k, by omega⟩)
    have e₂ := Classical.choice (P.triangle_obj₂ ⟨k, by omega⟩)
    have h₁ : Q.ExtensionClosure T.obj₁ := .of_iso e₁.symm hchain_k
    have h₃ : Q.ExtensionClosure T.obj₃ := .mem (hfactors ⟨k, by omega⟩)
    exact .of_iso e₂ (.ext hT h₁ h₃)

namespace Triangulated

variable (C : Type u) [Category.{v} C] [HasZeroObject C] [HasShift C ℤ]
  [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
  [IsTriangulated C]

/-! ### Extension-closed subcategories Q(> t), Q(≤ t) (Node 7.8a) -/

variable [IsTriangulated C] in
/-- Auxiliary: any morphism from a `Q(ψ)`-semistable object to the `k`-th chain object of a
`Q`-HN filtration whose phases are all strictly less than `ψ` is zero. This is the direct
`deformedPred` analogue of `Slicing.chain_hom_eq_zero_of_gt`. -/
lemma chain_hom_eq_zero_of_gt_deformed
    (σ : StabilityCondition C)
    (W : K₀ C →+ ℂ) (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    {ε₀ : ℝ} (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4) (hε₀8 : ε₀ < 1 / 8)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    {A E : C} {ψ : ℝ}
    (hA : σ.deformedPred C W hW ε₀ hε₀ hε₀2 hsin ψ A)
    (F : HNFiltration C (σ.deformedPred C W hW ε₀ hε₀ hε₀2 hsin) E)
    (hlt : ∀ i, F.φ i < ψ) :
    ∀ (k : ℕ) (hk : k < F.n + 1) (f : A ⟶ F.chain.obj ⟨k, hk⟩), f = 0 := by
  intro k
  induction k with
  | zero =>
      intro hk f
      exact (F.base_isZero : IsZero F.chain.left).eq_of_tgt f 0
  | succ k ih =>
      intro hk f
      have hkn : k < F.n := by omega
      let T := F.triangle ⟨k, hkn⟩
      let e₁ := Classical.choice (F.triangle_obj₁ ⟨k, hkn⟩)
      let e₂ := Classical.choice (F.triangle_obj₂ ⟨k, hkn⟩)
      have hcomp : (f ≫ e₂.inv) ≫ T.mor₂ = 0 :=
        σ.hom_eq_zero_of_deformedPred C W hW hε₀ hε₀2 hε₀8 hsin
          hA (F.semistable ⟨k, hkn⟩) (hlt ⟨k, hkn⟩) _
      obtain ⟨g, hg⟩ := Triangle.coyoneda_exact₂ T
        (F.triangle_dist ⟨k, hkn⟩) (f ≫ e₂.inv) hcomp
      have hg0 : g ≫ e₁.hom = 0 := ih (by omega) (g ≫ e₁.hom)
      have hg_eq : g = 0 := by
        have : g = (g ≫ e₁.hom) ≫ e₁.inv := by
          rw [Category.assoc, e₁.hom_inv_id, Category.comp_id]
        rw [this, hg0, zero_comp]
      have hfe : f ≫ e₂.inv = 0 := by rw [hg, hg_eq, zero_comp]
      have : f = (f ≫ e₂.inv) ≫ e₂.hom := by
        rw [Category.assoc, e₂.inv_hom_id, Category.comp_id]
      rw [this, hfe, zero_comp]

variable [IsTriangulated C] in
/-- A morphism from a `Q(ψ)`-semistable object to an HN-filtered object whose phases are all
strictly less than `ψ` is zero. -/
lemma hom_eq_zero_of_gt_phases_deformed
    (σ : StabilityCondition C)
    (W : K₀ C →+ ℂ) (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    {ε₀ : ℝ} (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4) (hε₀8 : ε₀ < 1 / 8)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    {A E : C} {ψ : ℝ}
    (hA : σ.deformedPred C W hW ε₀ hε₀ hε₀2 hsin ψ A)
    (F : HNFiltration C (σ.deformedPred C W hW ε₀ hε₀ hε₀2 hsin) E)
    (hlt : ∀ i, F.φ i < ψ) (f : A ⟶ E) : f = 0 := by
  let eE := Classical.choice F.top_iso
  have h1 : f ≫ eE.inv = 0 :=
    chain_hom_eq_zero_of_gt_deformed (C := C) (σ := σ) (W := W) (hW := hW)
      hε₀ hε₀2 hε₀8 hsin hA F hlt F.n (by omega) _
  have : f = (f ≫ eE.inv) ≫ eE.hom := by
    rw [Category.assoc, eE.inv_hom_id, Category.comp_id]
  rw [this, h1, zero_comp]

variable [IsTriangulated C] in
/-- Auxiliary: any morphism from the `k`-th chain object of a `Q`-HN filtration (with all
phases strictly greater than those of a second `Q`-HN filtration) to the target of the second
filtration is zero. This is the `deformedPred` analogue of
`Slicing.chain_hom_eq_zero_gap`. -/
lemma chain_hom_eq_zero_gap_deformed
    (σ : StabilityCondition C)
    (W : K₀ C →+ ℂ) (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    {ε₀ : ℝ} (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4) (hε₀8 : ε₀ < 1 / 8)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    {X Y : C}
    (Fx : HNFiltration C (σ.deformedPred C W hW ε₀ hε₀ hε₀2 hsin) X)
    (Fy : HNFiltration C (σ.deformedPred C W hW ε₀ hε₀ hε₀2 hsin) Y)
    (hgap : ∀ i j, Fy.φ j < Fx.φ i) :
    ∀ (k : ℕ) (hk : k < Fx.n + 1) (f : Fx.chain.obj ⟨k, hk⟩ ⟶ Y), f = 0 := by
  intro k
  induction k with
  | zero =>
      intro hk f
      exact (Fx.base_isZero : IsZero Fx.chain.left).eq_of_src f 0
  | succ k ih =>
      intro hk f
      have hkn : k < Fx.n := by omega
      let T := Fx.triangle ⟨k, hkn⟩
      let e₁ := Classical.choice (Fx.triangle_obj₁ ⟨k, hkn⟩)
      let e₂ := Classical.choice (Fx.triangle_obj₂ ⟨k, hkn⟩)
      have hmor1 : T.mor₁ ≫ (e₂.hom ≫ f) = 0 := by
        have h1 : e₁.inv ≫ (T.mor₁ ≫ (e₂.hom ≫ f)) = 0 := by
          simp only [← Category.assoc]
          exact ih (by omega) _
        have h2 :
            e₁.hom ≫ (e₁.inv ≫ (T.mor₁ ≫ (e₂.hom ≫ f))) =
              T.mor₁ ≫ (e₂.hom ≫ f) := by
          rw [← Category.assoc, e₁.hom_inv_id, Category.id_comp]
        rw [← h2, h1, comp_zero]
      obtain ⟨g, hg⟩ := Triangle.yoneda_exact₂ T
        (Fx.triangle_dist ⟨k, hkn⟩) (e₂.hom ≫ f) hmor1
      have hg_eq : g = 0 :=
        hom_eq_zero_of_gt_phases_deformed (C := C) (σ := σ) (W := W) (hW := hW)
          hε₀ hε₀2 hε₀8 hsin (Fx.semistable ⟨k, hkn⟩) Fy
          (fun j ↦ hgap ⟨k, hkn⟩ j) g
      have hef : e₂.hom ≫ f = 0 := by rw [hg, hg_eq, comp_zero]
      have : f = e₂.inv ≫ (e₂.hom ≫ f) := by
        rw [← Category.assoc, e₂.inv_hom_id, Category.id_comp]
      rw [this, hef, comp_zero]

variable [IsTriangulated C] in
/-- Morphisms between `Q`-HN filtered objects with a phase gap are zero. -/
lemma hom_eq_zero_of_phase_gap_deformed
    (σ : StabilityCondition C)
    (W : K₀ C →+ ℂ) (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    {ε₀ : ℝ} (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4) (hε₀8 : ε₀ < 1 / 8)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    {X Y : C}
    (Fx : HNFiltration C (σ.deformedPred C W hW ε₀ hε₀ hε₀2 hsin) X)
    (Fy : HNFiltration C (σ.deformedPred C W hW ε₀ hε₀ hε₀2 hsin) Y)
    (hgap : ∀ i j, Fy.φ j < Fx.φ i) (f : X ⟶ Y) : f = 0 := by
  let eX := Classical.choice Fx.top_iso
  have h1 : eX.hom ≫ f = 0 :=
    chain_hom_eq_zero_gap_deformed (C := C) (σ := σ) (W := W) (hW := hW)
      hε₀ hε₀2 hε₀8 hsin Fx Fy hgap Fx.n (by omega) _
  have : f = eX.inv ≫ (eX.hom ≫ f) := by
    rw [← Category.assoc, eX.inv_hom_id, Category.id_comp]
  rw [this, h1, comp_zero]

variable [IsTriangulated C] in
/-- Inside a thin interval whose `W`-phase window already sits `ε₀` away from the
boundaries, the Lemma 7.6 hom-vanishing theorem applies directly to the interval-semistable
objects, because they are `deformedPred` objects witnessed by that same interval. -/
theorem hom_eq_zero_of_enveloped_interval_semistable
    (σ : StabilityCondition C) (W : K₀ C →+ ℂ)
    (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    {a b ε₀ : ℝ} (hab : a < b)
    [Fact (a < b)] [Fact (b - a ≤ 1)]
    (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4) (hε₀8 : ε₀ < 1 / 8)
    (hthin : b - a + 2 * ε₀ < 1)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    (hWindow : ∀ {F : C}, σ.slicing.intervalProp C a b F → ¬IsZero F →
      a + ε₀ < wPhaseOf (W (K₀.of C F)) ((a + b) / 2) ∧
        wPhaseOf (W (K₀.of C F)) ((a + b) / 2) < b - ε₀)
    {E F : σ.slicing.IntervalCat C a b}
    (hE : (σ.skewedStabilityFunction_of_near C W hW hab).Semistable C E.obj
      (wPhaseOf (W (K₀.of C E.obj)) ((a + b) / 2)))
    (hF : (σ.skewedStabilityFunction_of_near C W hW hab).Semistable C F.obj
      (wPhaseOf (W (K₀.of C F.obj)) ((a + b) / 2)))
    (hlt :
      wPhaseOf (W (K₀.of C F.obj)) ((a + b) / 2) <
        wPhaseOf (W (K₀.of C E.obj)) ((a + b) / 2))
    (f : E ⟶ F) :
    f = 0 := by
  have hEQ :
      σ.deformedPred C W hW ε₀ hε₀ hε₀2 hsin
        (wPhaseOf (W (K₀.of C E.obj)) ((a + b) / 2)) E.obj := by
    refine Or.inr ⟨a, b, hab, hthin, ?_, ?_, ?_⟩
    · exact le_of_lt (hWindow E.property hE.2.1).1
    · exact le_of_lt (hWindow E.property hE.2.1).2
    · simpa using hE
  have hFQ :
      σ.deformedPred C W hW ε₀ hε₀ hε₀2 hsin
        (wPhaseOf (W (K₀.of C F.obj)) ((a + b) / 2)) F.obj := by
    refine Or.inr ⟨a, b, hab, hthin, ?_, ?_, ?_⟩
    · exact le_of_lt (hWindow F.property hF.2.1).1
    · exact le_of_lt (hWindow F.property hF.2.1).2
    · simpa using hF
  have h0 : f.hom = 0 :=
    σ.hom_eq_zero_of_deformedPred C W hW hε₀ hε₀2 hε₀8 hsin hEQ hFQ hlt f.hom
  ext
  exact h0

variable [IsTriangulated C] in
/-- Lemma 7.7 packaged directly for the deformed slicing: if a thin interval carries the
strict finite-length input and every nonzero object has `W`-phase at least `ε₀` away from
the interval boundaries, then the thin-interval HN factors are already `Q`-factors, using
the same interval as the witness in `deformedPred`. -/
theorem exists_deformedHN_of_enveloped_interval
    (σ : StabilityCondition C) (W : K₀ C →+ ℂ)
    (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    {a b ε₀ : ℝ} (hab : a < b)
    [Fact (a < b)] [Fact (b - a ≤ 1)]
    (hFiniteLength : ThinFiniteLengthInInterval (C := C) σ a b)
    (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4) (hε₀8 : ε₀ < 1 / 8)
    (hthin : b - a + 2 * ε₀ < 1)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    (hW_interval : ∀ {F : C}, σ.slicing.intervalProp C a b F → ¬IsZero F →
      W (K₀.of C F) ≠ 0)
    (hWindow : ∀ {F : C}, σ.slicing.intervalProp C a b F → ¬IsZero F →
      a + ε₀ < wPhaseOf (W (K₀.of C F)) ((a + b) / 2) ∧
        wPhaseOf (W (K₀.of C F)) ((a + b) / 2) < b - ε₀)
    {X : σ.slicing.IntervalCat C a b} (hX : ¬IsZero X) :
    ∃ G : HNFiltration C (σ.deformedPred C W hW ε₀ hε₀ hε₀2 hsin) X.obj,
      ∀ j, a + ε₀ < G.φ j ∧ G.φ j < b - ε₀ := by
  let ssf : SkewedStabilityFunction C σ.slicing a b :=
    σ.skewedStabilityFunction_of_near C W hW hab
  obtain ⟨G, hGφ⟩ :=
    SkewedStabilityFunction.hn_exists_in_thin_interval
      (C := C) (σ := σ) (a := a) (b := b) (ssf := ssf) hFiniteLength
      (fun {F} hF hFne ↦ hW_interval hF hFne)
      (L := a + ε₀) (U := b - ε₀)
      (fun {F} hF hFne ↦ hWindow hF hFne)
      (by linarith [hthin])
      (fun {E F} hE hF hlt f ↦
        hom_eq_zero_of_enveloped_interval_semistable
          (C := C) (σ := σ) (W := W) (hW := hW) hab
          hε₀ hε₀2 hε₀8 hthin hsin hWindow hE hF hlt f) X hX
  let GQ : HNFiltration C (σ.deformedPred C W hW ε₀ hε₀ hε₀2 hsin) X.obj :=
    { n := G.n
      chain := G.chain
      triangle := G.triangle
      triangle_dist := G.triangle_dist
      triangle_obj₁ := G.triangle_obj₁
      triangle_obj₂ := G.triangle_obj₂
      base_isZero := G.base_isZero
      top_iso := G.top_iso
      zero_isZero := G.zero_isZero
      φ := G.φ
      hφ := G.hφ
      semistable := fun j ↦ by
        change IsZero (G.factor j) ∨
          ∃ (a' b' : ℝ) (hab' : a' < b') (_ : b' - a' + 2 * ε₀ < 1)
            (_ : a' + ε₀ ≤ G.φ j) (_ : G.φ j ≤ b' - ε₀),
            (σ.skewedStabilityFunction_of_near C W hW hab').Semistable C (G.factor j) (G.φ j)
        refine Or.inr ⟨a, b, hab, hthin, le_of_lt (hGφ j).1, le_of_lt (hGφ j).2, ?_⟩
        simpa [ssf] using G.semistable j }
  refine ⟨GQ, hGφ⟩

/-- **Generators of Q(> t)**: Q-semistable objects with some phase `ψ > t`
(Bridgeland Node 7.8a). -/
def StabilityCondition.deformedGtGen (σ : StabilityCondition C)
    (W : K₀ C →+ ℂ) (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    (ε₀ : ℝ) (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    (t : ℝ) : ObjectProperty C :=
  fun E ↦ ∃ ψ, t < ψ ∧ σ.deformedPred C W hW ε₀ hε₀ hε₀2 hsin ψ E

/-- **Generators of Q(≤ t)**: Q-semistable objects with some phase `ψ ≤ t`
(Bridgeland Node 7.8a). -/
def StabilityCondition.deformedLeGen (σ : StabilityCondition C)
    (W : K₀ C →+ ℂ) (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    (ε₀ : ℝ) (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    (t : ℝ) : ObjectProperty C :=
  fun E ↦ ∃ ψ, ψ ≤ t ∧ σ.deformedPred C W hW ε₀ hε₀ hε₀2 hsin ψ E

/-- **Generators of Q(< t)**: Q-semistable objects with some phase `ψ < t`
(Bridgeland Node 7.8a / 7.9). -/
def StabilityCondition.deformedLtGen (σ : StabilityCondition C)
    (W : K₀ C →+ ℂ) (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    (ε₀ : ℝ) (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    (t : ℝ) : ObjectProperty C :=
  fun E ↦ ∃ ψ, ψ < t ∧ σ.deformedPred C W hW ε₀ hε₀ hε₀2 hsin ψ E

/-- **Q(> t)**: the extension-closed subcategory generated by the `Q(ψ)` with `ψ > t`
(Bridgeland p.6, Node 7.8a). -/
def StabilityCondition.deformedGtPred (σ : StabilityCondition C)
    (W : K₀ C →+ ℂ) (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    (ε₀ : ℝ) (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    (t : ℝ) : ObjectProperty C :=
  (σ.deformedGtGen C W hW ε₀ hε₀ hε₀2 hsin t).ExtensionClosure

/-- **Q(≤ t)**: the extension-closed subcategory generated by the `Q(ψ)` with `ψ ≤ t`
(Bridgeland p.6, Node 7.8a). -/
def StabilityCondition.deformedLePred (σ : StabilityCondition C)
    (W : K₀ C →+ ℂ) (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    (ε₀ : ℝ) (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    (t : ℝ) : ObjectProperty C :=
  (σ.deformedLeGen C W hW ε₀ hε₀ hε₀2 hsin t).ExtensionClosure

/-- **Q(< t)**: the extension-closed subcategory generated by the `Q(ψ)` with `ψ < t`
(Bridgeland p.6, Node 7.8a / 7.9). -/
def StabilityCondition.deformedLtPred (σ : StabilityCondition C)
    (W : K₀ C →+ ℂ) (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    (ε₀ : ℝ) (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    (t : ℝ) : ObjectProperty C :=
  (σ.deformedLtGen C W hW ε₀ hε₀ hε₀2 hsin t).ExtensionClosure

variable [IsTriangulated C] in
/-- Monotonicity of the provisional `Q(≤ t)` predicate. -/
theorem StabilityCondition.deformedLePred_mono
    (σ : StabilityCondition C)
    (W : K₀ C →+ ℂ) (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    {ε₀ : ℝ} (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    {t₁ t₂ : ℝ} (ht : t₁ ≤ t₂) :
    σ.deformedLePred C W hW ε₀ hε₀ hε₀2 hsin t₁ ≤
      σ.deformedLePred C W hW ε₀ hε₀ hε₀2 hsin t₂ :=
  ObjectProperty.ExtensionClosure.mono (fun E ⟨ψ, hψ, hP⟩ ↦ ⟨ψ, le_trans hψ ht, hP⟩)

variable [IsTriangulated C] in
/-- Monotonicity of the provisional `Q(< t)` predicate. -/
theorem StabilityCondition.deformedLtPred_mono
    (σ : StabilityCondition C)
    (W : K₀ C →+ ℂ) (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    {ε₀ : ℝ} (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    {t₁ t₂ : ℝ} (ht : t₁ ≤ t₂) :
    σ.deformedLtPred C W hW ε₀ hε₀ hε₀2 hsin t₁ ≤
      σ.deformedLtPred C W hW ε₀ hε₀ hε₀2 hsin t₂ :=
  ObjectProperty.ExtensionClosure.mono (fun E ⟨ψ, hψ, hP⟩ ↦ ⟨ψ, lt_of_lt_of_le hψ ht, hP⟩)

variable [IsTriangulated C] in
/-- Any `Q(< t)`-object is in `Q(≤ t)`. -/
theorem StabilityCondition.deformedLePred_of_deformedLtPred
    (σ : StabilityCondition C)
    (W : K₀ C →+ ℂ) (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    {ε₀ : ℝ} (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    {t : ℝ} :
    σ.deformedLtPred C W hW ε₀ hε₀ hε₀2 hsin t ≤
      σ.deformedLePred C W hW ε₀ hε₀ hε₀2 hsin t :=
  ObjectProperty.ExtensionClosure.mono (fun E ⟨ψ, hψ, hP⟩ ↦ ⟨ψ, le_of_lt hψ, hP⟩)

variable [IsTriangulated C] in
/-- Anti-monotonicity of `Q(> t)`: if `t₁ ≤ t₂` then `Q(> t₂) ⊆ Q(> t₁)`. -/
theorem StabilityCondition.deformedGtPred_anti
    (σ : StabilityCondition C)
    (W : K₀ C →+ ℂ) (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    {ε₀ : ℝ} (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    {t₁ t₂ : ℝ} (ht : t₁ ≤ t₂) :
    σ.deformedGtPred C W hW ε₀ hε₀ hε₀2 hsin t₂ ≤
      σ.deformedGtPred C W hW ε₀ hε₀ hε₀2 hsin t₁ :=
  ObjectProperty.ExtensionClosure.mono (fun E ⟨ψ, hψ, hP⟩ ↦ ⟨ψ, lt_of_le_of_lt ht hψ, hP⟩)

variable [IsTriangulated C] in
/-- A length-one HN filtration presents the ambient object as isomorphic to its unique factor.
Hence, if the phase predicate is closed under isomorphisms, the ambient object is semistable
of that same phase. -/
theorem semistable_of_hn_length_one
    {P : ℝ → ObjectProperty C}
    (hPiso : ∀ φ : ℝ, (P φ).IsClosedUnderIsomorphisms)
    {Y : C} (GY : HNFiltration C P Y) (h1 : GY.n = 1) :
    P (GY.φ ⟨0, by omega⟩) Y := by
  let j0 : Fin GY.n := ⟨0, by omega⟩
  let T := GY.triangle j0
  have hZ1 : IsZero T.obj₁ :=
    IsZero.of_iso GY.base_isZero (Classical.choice (GY.triangle_obj₁ j0))
  have hIso₂ : IsIso T.mor₂ :=
    (Triangle.isZero₁_iff_isIso₂ T (GY.triangle_dist j0)).mp hZ1
  have hobj₂_eq : GY.chain.obj' (0 + 1) (by omega) = GY.chain.obj (Fin.last GY.n) :=
    congrArg GY.chain.obj (Fin.ext (by simp [Fin.last, h1]))
  let e₂Y : T.obj₂ ≅ Y :=
    (Classical.choice (GY.triangle_obj₂ j0)).trans
      ((eqToIso hobj₂_eq).trans (Classical.choice GY.top_iso))
  letI : (P (GY.φ j0)).IsClosedUnderIsomorphisms := hPiso (GY.φ j0)
  exact (P (GY.φ j0)).prop_of_iso ((e₂Y.symm.trans (asIso T.mor₂)).symm) (GY.semistable j0)

variable [IsTriangulated C] in
/-- Concatenate HN filtrations across a distinguished triangle `X → E → Y → X[1]`,
provided every phase in the filtration on `Y` is strictly smaller than every phase in the
filtration on `X`. This is the generic Postnikov-splicing step needed to assemble the
faithful Section 7 HN filtration from filtrations on successive σ-semistable factors. -/
theorem append_hn_filtration_of_triangle
    {P : ℝ → ObjectProperty C} {X E Y : C}
    (hPiso : ∀ φ : ℝ, (P φ).IsClosedUnderIsomorphisms)
    (GX : HNFiltration C P X)
    (GY : HNFiltration C P Y)
    (f : X ⟶ E) (g : E ⟶ Y) (h : Y ⟶ X⟦(1 : ℤ)⟧)
    (hT : Triangle.mk f g h ∈ distTriang C)
    (t : ℝ)
    (hX_gt : ∀ j : Fin GX.n, t < GX.φ j)
    (hY_gt : ∀ i : Fin GY.n, t < GY.φ i)
    (hsep : ∀ i : Fin GY.n, ∀ j : Fin GX.n, GY.φ i < GX.φ j) :
    ∃ G : HNFiltration C P E, ∀ j : Fin G.n, t < G.φ j := by
  suffices hmain :
      ∀ (m : ℕ) {Y : C} (GY : HNFiltration C P Y), GY.n ≤ m →
        ∀ {E : C} (f : X ⟶ E) (g : E ⟶ Y) (h : Y ⟶ X⟦(1 : ℤ)⟧),
          Triangle.mk f g h ∈ distTriang C →
          ∀ (t : ℝ),
          (∀ j : Fin GX.n, t < GX.φ j) →
          (∀ i : Fin GY.n, t < GY.φ i) →
          (∀ i : Fin GY.n, ∀ j : Fin GX.n, GY.φ i < GX.φ j) →
          ∃ G : HNFiltration C P E, ∀ j : Fin G.n, t < G.φ j by
    exact hmain GY.n GY le_rfl f g h hT t hX_gt hY_gt hsep
  intro m
  induction m with
  | zero =>
      intro Y GY hn E f g h hT t hX_gt hY_gt hsep
      have hYn : GY.n = 0 := by omega
      have hYz : IsZero Y := GY.zero_isZero hYn
      haveI : IsIso f := (Triangle.isZero₃_iff_isIso₁ _ hT).mp hYz
      refine ⟨GX.ofIso C (asIso f), ?_⟩
      intro j
      simpa using hX_gt j
  | succ m ih =>
      intro Y GY hn E f g h hT t hX_gt hY_gt hsep
      by_cases hYn : GY.n = 0
      · have hYz : IsZero Y := GY.zero_isZero hYn
        haveI : IsIso f := (Triangle.isZero₃_iff_isIso₁ _ hT).mp hYz
        refine ⟨GX.ofIso C (asIso f), ?_⟩
        intro j
        simpa using hX_gt j
      · have hYpos : 0 < GY.n := Nat.pos_of_ne_zero hYn
        by_cases hYone : GY.n = 1
        · let j0 : Fin GY.n := ⟨0, by omega⟩
          have hsep0 : ∀ j : Fin GX.n, GY.φ j0 < GX.φ j := by
            intro j
            exact hsep j0 j
          have hYss : P (GY.φ j0) Y :=
            semistable_of_hn_length_one (C := C) hPiso GY hYone
          refine ⟨GX.appendFactor C (Triangle.mk f g h) hT (Iso.refl _) (Iso.refl _)
            (GY.φ j0) hYss hsep0, ?_⟩
          intro j
          by_cases hj : j.val < GX.n
          · have hsmall :
                GY.φ j0 <
                  (GX.appendFactor C (Triangle.mk f g h) hT (Iso.refl _) (Iso.refl _)
                    (GY.φ j0) hYss hsep0).φ j := by
              simpa [HNFiltration.appendFactor, hj] using hsep0 ⟨j.val, hj⟩
            exact lt_trans (hY_gt j0) hsmall
          · have hjLast :
                (GX.appendFactor C (Triangle.mk f g h) hT (Iso.refl _) (Iso.refl _)
                  (GY.φ j0) hYss hsep0).φ j = GY.φ j0 := by
              simp [HNFiltration.appendFactor, hj]
            exact hjLast.symm ▸ hY_gt j0
        · have hYtwo : 2 ≤ GY.n := by omega
          let jLast : Fin GY.n := ⟨GY.n - 1, by omega⟩
          let GY' := GY.prefix C (GY.n - 1) (by omega) (by omega)
          let Tlast := GY.triangle jLast
          let e₁ := Classical.choice (GY.triangle_obj₁ jLast)
          let e₂ := Classical.choice (GY.triangle_obj₂ jLast)
          let eY := by
            have hchainN : GY.chain.obj' (GY.n - 1 + 1) (by omega) =
                GY.chain.obj (Fin.last GY.n) :=
              congrArg GY.chain.obj (Fin.ext (by simp [Fin.last]; omega))
            exact e₂.trans ((eqToIso hchainN).trans (Classical.choice GY.top_iso))
          let f23 : GY.chain.obj ⟨GY.n - 1, by omega⟩ ⟶ Y :=
            e₁.inv ≫ Tlast.mor₁ ≫ eY.hom
          let g23 : Y ⟶ Tlast.obj₃ :=
            eY.inv ≫ Tlast.mor₂
          let h23 : Tlast.obj₃ ⟶ GY.chain.obj ⟨GY.n - 1, by omega⟩⟦(1 : ℤ)⟧ :=
            Tlast.mor₃ ≫ e₁.hom⟦(1 : ℤ)⟧'
          have hT23 : Triangle.mk f23 g23 h23 ∈ distTriang C := by
            refine isomorphic_distinguished _ (GY.triangle_dist jLast) _ ?_
            exact Triangle.isoMk _ _ e₁.symm eY.symm (Iso.refl _)
              (by simp [Tlast, f23, eY])
              (by simp [Tlast, g23, eY])
              (by simp [Tlast, h23])
          obtain ⟨Z, f13, h13, hT13⟩ := distinguished_cocone_triangle₁ (g ≫ g23)
          let oct := Triangulated.someOctahedron'
            (show g ≫ g23 = g ≫ g23 by rfl) hT hT23 hT13
          have hsep' :
              ∀ i : Fin GY'.n, ∀ j : Fin GX.n, GY'.φ i < GX.φ j := by
            intro i j
            have hEqn : GY'.n = GY.n - 1 := rfl
            have hi : i.val < GY.n - 1 := by
              simpa [hEqn] using i.is_lt
            exact hsep ⟨i.val, by omega⟩ j
          have hX_gt_last : ∀ j : Fin GX.n, GY.φ jLast < GX.φ j := by
            intro j
            exact hsep jLast j
          have hY'_gt_last : ∀ i : Fin GY'.n, GY.φ jLast < GY'.φ i := by
            intro i
            have hEqn : GY'.n = GY.n - 1 := rfl
            have hi : i.val < GY.n - 1 := by
              simpa [hEqn] using i.is_lt
            change GY.φ jLast < GY.φ ⟨i.val, by omega⟩
            exact GY.hφ (show (⟨i.val, by omega⟩ : Fin GY.n) < jLast by
              exact Fin.mk_lt_mk.mpr (by omega))
          obtain ⟨GZ, hGZ⟩ := ih GY' (by
            change GY.n - 1 ≤ m
            omega) oct.triangle.mor₁ oct.triangle.mor₂ oct.triangle.mor₃ oct.mem
            (GY.φ jLast) hX_gt_last hY'_gt_last hsep'
          have hlast_gt_t : t < GY.φ jLast := hY_gt jLast
          refine ⟨GZ.appendFactor C (Triangle.mk f13 (g ≫ g23) h13) hT13
            (Iso.refl _) (Iso.refl _) (GY.φ jLast) (GY.semistable jLast) hGZ, ?_⟩
          intro j
          by_cases hj : j.val < GZ.n
          · have hsmall :
                GY.φ jLast <
                  (GZ.appendFactor C (Triangle.mk f13 (g ≫ g23) h13) hT13
                    (Iso.refl _) (Iso.refl _) (GY.φ jLast) (GY.semistable jLast)
                    hGZ).φ j := by
              simpa [HNFiltration.appendFactor, hj] using hGZ ⟨j.val, hj⟩
            exact lt_trans hlast_gt_t hsmall
          · have hjLast :
                (GZ.appendFactor C (Triangle.mk f13 (g ≫ g23) h13) hT13
                  (Iso.refl _) (Iso.refl _) (GY.φ jLast) (GY.semistable jLast) hGZ).φ j =
                    GY.φ jLast := by
              simp [HNFiltration.appendFactor, hj]
            exact hjLast.symm ▸ hlast_gt_t

variable [IsTriangulated C] in
/-- Split an HN filtration at an arbitrary cutoff `t`. The `X`-part carries a filtration whose
phases are all `> t`, and the `Y`-part carries a filtration whose phases are all `≤ t`.

The strengthened conclusion tracks that every phase of the `Y`-part is bounded below by the
last phase of the original filtration. This is the generic cutoff invariant needed to append the
last factor in the mixed case, exactly as in Bridgeland's p.24 argument. -/
theorem split_hn_filtration_at_cutoff
    {P : ℝ → ObjectProperty C} {A : C}
    (F : HNFiltration C P A) (t : ℝ) :
    ∃ (X Y : C) (GX : HNFiltration C P X) (GY : HNFiltration C P Y)
      (f : X ⟶ A) (g : A ⟶ Y) (h : Y ⟶ X⟦(1 : ℤ)⟧),
      Triangle.mk f g h ∈ distTriang C ∧
      (∀ j : Fin GX.n, t < GX.φ j) ∧
      (∀ j : Fin GY.n, GY.φ j ≤ t) ∧
      (∀ (_ : 0 < F.n) (j : Fin GY.n),
        F.φ ⟨F.n - 1, by omega⟩ ≤ GY.φ j) := by
  suffices hmain :
      ∀ (m : ℕ) (A : C) (F : HNFiltration C P A), F.n ≤ m →
        ∃ (X Y : C) (GX : HNFiltration C P X) (GY : HNFiltration C P Y)
          (f : X ⟶ A) (g : A ⟶ Y) (h : Y ⟶ X⟦(1 : ℤ)⟧),
          Triangle.mk f g h ∈ distTriang C ∧
          (∀ j : Fin GX.n, t < GX.φ j) ∧
          (∀ j : Fin GY.n, GY.φ j ≤ t) ∧
          (∀ (_ : 0 < F.n) (j : Fin GY.n),
            F.φ ⟨F.n - 1, by omega⟩ ≤ GY.φ j) by
    exact hmain F.n A F le_rfl
  intro m
  induction m with
  | zero =>
      intro A F hFn
      have hn : F.n = 0 := by omega
      refine ⟨A, 0, F, HNFiltration.zero C (P := P) 0 (isZero_zero C),
        𝟙 A, 0, 0, contractible_distinguished A, ?_, ?_, ?_⟩
      · intro j
        exact False.elim (by simpa [hn] using j.is_lt)
      · intro j
        exact Fin.elim0 j
      · intro hn0 j
        exact False.elim (by omega)
  | succ m ih =>
      intro A F hFn
      by_cases hn : F.n = 0
      · refine ⟨A, 0, F, HNFiltration.zero C (P := P) 0 (isZero_zero C),
          𝟙 A, 0, 0, contractible_distinguished A, ?_, ?_, ?_⟩
        · intro j
          exact False.elim (by simpa [hn] using j.is_lt)
        · intro j
          exact Fin.elim0 j
        · intro hn0 j
          exact False.elim (by omega)
      · have hn0 : 0 < F.n := Nat.pos_of_ne_zero hn
        by_cases hlast_gt : t < F.φ ⟨F.n - 1, by omega⟩
        · refine ⟨A, 0, F, HNFiltration.zero C (P := P) 0 (isZero_zero C),
            𝟙 A, 0, 0, contractible_distinguished A, ?_, ?_, ?_⟩
          · intro j
            exact lt_of_lt_of_le hlast_gt
              (F.hφ.antitone (Fin.mk_le_mk.mpr (by omega)))
          · intro j
            exact Fin.elim0 j
          · intro _ j
            exact Fin.elim0 j
        · have hlast_le : F.φ ⟨F.n - 1, by omega⟩ ≤ t := by
            linarith
          by_cases hFone : F.n = 1
          · refine ⟨0, A, HNFiltration.zero C (P := P) 0 (isZero_zero C), F,
              0, 𝟙 A, 0, contractible_distinguished₁ A, ?_, ?_, ?_⟩
            · intro j
              exact Fin.elim0 j
            · intro j
              have hj : j = ⟨0, by omega⟩ := by
                apply Fin.ext
                omega
              subst j
              simpa [HNFiltration.phiPlus, hFone] using hlast_le
            · intro _ j
              have hj : j = ⟨0, by omega⟩ := by
                apply Fin.ext
                omega
              subst j
              simpa [hFone]
          · have hn2 : 2 ≤ F.n := by omega
            let G := F.prefix C (F.n - 1) (by omega) (by omega)
            obtain ⟨X, Y', GX, GY', f', g', h', hT', hGX_gt, hGY'_le, hGY'_bound⟩ :=
              ih (F.chain.obj' (F.n - 1) (by omega)) G
                (by
                  change F.n - 1 ≤ m
                  omega)
            let T := F.triangle ⟨F.n - 1, by omega⟩
            let e₁ := Classical.choice (F.triangle_obj₁ ⟨F.n - 1, by omega⟩)
            let e₂ := Classical.choice (F.triangle_obj₂ ⟨F.n - 1, by omega⟩)
            let eA := Classical.choice F.top_iso
            have hchainN : F.chain.obj' (F.n - 1 + 1) (by omega) =
                F.chain.obj (Fin.last F.n) :=
              congrArg F.chain.obj (Fin.ext (by simp [Fin.last]; omega))
            let e₂A : T.obj₂ ≅ A :=
              e₂.trans ((eqToIso hchainN).trans eA)
            let u₂₃ : F.chain.obj' (F.n - 1) (by omega) ⟶ A :=
              e₁.inv ≫ T.mor₁ ≫ e₂A.hom
            let Tisoₘ := Triangle.isoMk
              (Triangle.mk u₂₃ (e₂A.inv ≫ T.mor₂) (T.mor₃ ≫ e₁.hom⟦(1 : ℤ)⟧')) T
              e₁.symm e₂A.symm (Iso.refl _)
              (by simp [u₂₃, e₂A])
              (by simp [e₂A])
              (by simp)
            have hTu₂₃ :
                Triangle.mk u₂₃ (e₂A.inv ≫ T.mor₂) (T.mor₃ ≫ e₁.hom⟦(1 : ℤ)⟧') ∈
                  distTriang C :=
              isomorphic_distinguished _ (F.triangle_dist ⟨F.n - 1, by omega⟩) _ Tisoₘ
            have hGn : 0 < G.n := by
              change 0 < F.n - 1
              omega
            have hφlast_lt : ∀ j : Fin GY'.n, F.φ ⟨F.n - 1, by omega⟩ < GY'.φ j := by
              intro j
              calc
                F.φ ⟨F.n - 1, by omega⟩
                    < F.φ ⟨F.n - 2, by omega⟩ :=
                  F.hφ (show (⟨F.n - 2, by omega⟩ : Fin F.n) <
                    ⟨F.n - 1, by omega⟩ from
                      Fin.mk_lt_mk.mpr (by omega))
                _ = G.φ ⟨G.n - 1, by omega⟩ := by
                    change F.φ ⟨F.n - 2, _⟩ = F.φ ⟨(F.n - 1) - 1, _⟩
                    congr 1
                _ ≤ GY'.φ j := hGY'_bound hGn j
            obtain ⟨Z, v₁₃, w₁₃, h₁₃⟩ := distinguished_cocone_triangle (f' ≫ u₂₃)
            let oct := Triangulated.someOctahedron rfl hT' hTu₂₃ h₁₃
            let GZ := GY'.appendFactor C oct.triangle oct.mem (Iso.refl _)
              (Iso.refl _) (F.φ ⟨F.n - 1, by omega⟩)
              (F.semistable ⟨F.n - 1, by omega⟩) hφlast_lt
            refine ⟨X, Z, GX, GZ, f' ≫ u₂₃, v₁₃, w₁₃, h₁₃, hGX_gt, ?_, ?_⟩
            · intro j
              change GZ.φ j ≤ t
              simp only [GZ, HNFiltration.appendFactor]
              split_ifs with hj
              · exact hGY'_le ⟨j.val, hj⟩
              · exact hlast_le
            · intro _ j
              change F.φ ⟨F.n - 1, by omega⟩ ≤ GZ.φ j
              simp only [GZ, HNFiltration.appendFactor]
              split_ifs with hj
              · exact le_of_lt (hφlast_lt ⟨j.val, hj⟩)
              · exact le_rfl


variable [IsTriangulated C] in
/-- **Orthogonality of Q(> t) and Q(≤ t)** (**Node 7.8b**). Every morphism from a
`Q(> t)`-object to a `Q(≤ t)`-object is zero, by the sharp hom-vanishing (Node 7.6). -/
theorem StabilityCondition.hom_eq_zero_of_deformedGt_deformedLe
    (σ : StabilityCondition C)
    (W : K₀ C →+ ℂ) (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    {ε₀ : ℝ} (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4)
    (hε₀8 : ε₀ < 1 / 8)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    {E F : C} {t : ℝ}
    (hE : σ.deformedGtPred C W hW ε₀ hε₀ hε₀2 hsin t E)
    (hF : σ.deformedLePred C W hW ε₀ hε₀ hε₀2 hsin t F)
    (f : E ⟶ F) : f = 0 :=
  ObjectProperty.ExtensionClosure.hom_eq_zero
    (fun E F ⟨ψ₁, hψ₁, hE'⟩ ⟨ψ₂, hψ₂, hF'⟩ f ↦
      σ.hom_eq_zero_of_deformedPred C W hW hε₀ hε₀2 hε₀8 hsin hE' hF' (by linarith) f)
    hE hF f

variable [IsTriangulated C] in
/-- Orthogonality of `Q(> t)` and `Q(< t)`. This is the strict version of Node 7.8b used
later for the strip categories `Q((t, t + δ))`. -/
theorem StabilityCondition.hom_eq_zero_of_deformedGt_deformedLt
    (σ : StabilityCondition C)
    (W : K₀ C →+ ℂ) (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    {ε₀ : ℝ} (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4)
    (hε₀8 : ε₀ < 1 / 8)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    {E F : C} {t : ℝ}
    (hE : σ.deformedGtPred C W hW ε₀ hε₀ hε₀2 hsin t E)
    (hF : σ.deformedLtPred C W hW ε₀ hε₀ hε₀2 hsin t F)
    (f : E ⟶ F) : f = 0 :=
  ObjectProperty.ExtensionClosure.hom_eq_zero
    (fun E F ⟨ψ₁, hψ₁, hE'⟩ ⟨ψ₂, hψ₂, hF'⟩ f ↦
      σ.hom_eq_zero_of_deformedPred C W hW hε₀ hε₀2 hε₀8 hsin hE' hF' (by linarith) f)
    hE hF f
variable [IsTriangulated C] in
/-- A `Q`-HN filtration split at cutoff `t` gives the paper's truncation triangle whose two
pieces lie in `Q(> t)` and `Q(≤ t)`. -/
theorem exists_deformedGt_deformedLe_triangle_of_hn
    (σ : StabilityCondition C)
    (W : K₀ C →+ ℂ) (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    {ε₀ : ℝ} (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    {E : C}
    (G : HNFiltration C (σ.deformedPred C W hW ε₀ hε₀ hε₀2 hsin) E)
    (t : ℝ) :
    ∃ (X Y : C) (f : X ⟶ E) (g : E ⟶ Y) (h : Y ⟶ X⟦(1 : ℤ)⟧),
      Triangle.mk f g h ∈ distTriang C ∧
      σ.deformedGtPred C W hW ε₀ hε₀ hε₀2 hsin t X ∧
      σ.deformedLePred C W hW ε₀ hε₀ hε₀2 hsin t Y := by
  obtain ⟨X, Y, GX, GY, f, g, h, hT, hGX, hGY, _⟩ :=
    split_hn_filtration_at_cutoff (C := C) G t
  exact ⟨X, Y, f, g, h, hT,
    ObjectProperty.ExtensionClosure.of_postnikovTower GX.toPostnikovTower
      (fun j ↦ ⟨GX.φ j, hGX j, GX.semistable j⟩),
    ObjectProperty.ExtensionClosure.of_postnikovTower GY.toPostnikovTower
      (fun j ↦ ⟨GY.φ j, hGY j, GY.semistable j⟩)⟩

variable [IsTriangulated C] in
/-- A `Q`-HN filtration split at cutoff `t` also gives the strip-style truncation triangle
used in Node 7.9, with the right-hand term in `Q(< t + δ)` for any `δ > 0`. -/
theorem exists_deformedGt_deformedLt_triangle_of_hn
    (σ : StabilityCondition C)
    (W : K₀ C →+ ℂ) (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    {ε₀ : ℝ} (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    {E : C}
    (G : HNFiltration C (σ.deformedPred C W hW ε₀ hε₀ hε₀2 hsin) E)
    (t δ : ℝ) (hδ : 0 < δ) :
    ∃ (X Y : C) (f : X ⟶ E) (g : E ⟶ Y) (h : Y ⟶ X⟦(1 : ℤ)⟧),
      Triangle.mk f g h ∈ distTriang C ∧
      σ.deformedGtPred C W hW ε₀ hε₀ hε₀2 hsin t X ∧
      σ.deformedLtPred C W hW ε₀ hε₀ hε₀2 hsin (t + δ) Y := by
  obtain ⟨X, Y, f, g, h, hT, hX, hY⟩ :=
    exists_deformedGt_deformedLe_triangle_of_hn C σ W hW hε₀ hε₀2 hsin G t
  exact ⟨X, Y, f, g, h, hT, hX,
    ObjectProperty.ExtensionClosure.mono (fun E ⟨ψ, hψ, hP⟩ ↦ ⟨ψ, by linarith, hP⟩) _ hY⟩

variable [IsTriangulated C] in
/-- Faithful Node 7.8c wrapper: once an object in a thin interval admits a `Q`-HN filtration
whose factors stay inside the same enveloping window, splitting that HN filtration at a cutoff
`t` gives the paper's `Q(> t) / Q(≤ t)` truncation triangle. -/
theorem exists_deformedGt_deformedLe_triangle_of_enveloped_interval
    (σ : StabilityCondition C)
    (W : K₀ C →+ ℂ) (hW : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal 1)
    {a b ε₀ : ℝ} (hab : a < b)
    [Fact (a < b)] [Fact (b - a ≤ 1)]
    (hFiniteLength : ThinFiniteLengthInInterval (C := C) σ a b)
    (hε₀ : 0 < ε₀) (hε₀2 : ε₀ < 1 / 4) (hε₀8 : ε₀ < 1 / 8)
    (hthin : b - a + 2 * ε₀ < 1)
    (hsin : stabSeminorm C σ (W - σ.Z) < ENNReal.ofReal (Real.sin (Real.pi * ε₀)))
    (hW_interval : ∀ {F : C}, σ.slicing.intervalProp C a b F → ¬IsZero F →
      W (K₀.of C F) ≠ 0)
    (hWindow : ∀ {F : C}, σ.slicing.intervalProp C a b F → ¬IsZero F →
      a + ε₀ < wPhaseOf (W (K₀.of C F)) ((a + b) / 2) ∧
        wPhaseOf (W (K₀.of C F)) ((a + b) / 2) < b - ε₀)
    {E : C} (hE : σ.slicing.intervalProp C a b E) (hEne : ¬IsZero E)
    (t : ℝ) :
    ∃ (X Y : C) (f : X ⟶ E) (g : E ⟶ Y) (h : Y ⟶ X⟦(1 : ℤ)⟧),
      Triangle.mk f g h ∈ distTriang C ∧
      σ.deformedGtPred C W hW ε₀ hε₀ hε₀2 hsin t X ∧
      σ.deformedLePred C W hW ε₀ hε₀ hε₀2 hsin t Y := by
  let EI : σ.slicing.IntervalCat C a b := ⟨E, hE⟩
  have hEIne : ¬IsZero EI := by
    intro hZ
    exact hEne (((σ.slicing.intervalProp C a b).ι).map_isZero hZ)
  obtain ⟨G, _hGφ⟩ :=
    exists_deformedHN_of_enveloped_interval
      (C := C) (σ := σ) (W := W) (hW := hW) hab
      hFiniteLength hε₀ hε₀2 hε₀8 hthin hsin hW_interval hWindow
      (X := EI) hEIne
  exact exists_deformedGt_deformedLe_triangle_of_hn
    (C := C) (σ := σ) (W := W) (hW := hW) hε₀ hε₀2 hsin G t


end CategoryTheory.Triangulated
