/-
Copyright (c) 2026 Mathlib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Formalization
-/
import Mathlib.CategoryTheory.Triangulated.Pretriangulated
import Mathlib.GroupTheory.FreeAbelianGroup
import Mathlib.GroupTheory.QuotientGroup.Defs

/-!
# Grothendieck Group of a Triangulated Category

We define the Grothendieck group `K₀ C` of a pretriangulated category `C` as the free abelian
group on objects of `C` modulo the distinguished triangle relations:
`[B] = [A] + [C]` for each distinguished triangle `A → B → C → A⟦1⟧`.

The isomorphism relation `[X] = [Y]` for `X ≅ Y` is derivable from the triangle relations
(via the distinguished triangle `X → Y → 0 → X⟦1⟧`), so we do not include it as a separate
generator.

## Main definitions

* `CategoryTheory.Triangulated.K₀Subgroup`: the subgroup of triangle relations
* `CategoryTheory.Triangulated.K₀`: the Grothendieck group with its `AddCommGroup` instance
* `CategoryTheory.Triangulated.K₀.of`: the class map `C → K₀ C`
* `CategoryTheory.Triangulated.K₀.of_triangle`: additivity on distinguished triangles
* `CategoryTheory.Triangulated.IsTriangleAdditive`: typeclass for functions `C → A` that
  respect distinguished triangle relations
* `CategoryTheory.Triangulated.K₀.lift`: the universal property of `K₀`
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits
open scoped ZeroObject

universe v u

namespace CategoryTheory.Triangulated

variable (C : Type u) [Category.{v} C] [HasZeroObject C] [HasShift C ℤ]
  [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]

/-- The subgroup of `FreeAbelianGroup C` generated by the distinguished triangle relations:
`[T.obj₂] - [T.obj₁] - [T.obj₃]` for each distinguished triangle `T`.

The isomorphism relations `[X] - [Y]` for `X ≅ Y` are derivable, since any isomorphism
gives rise to a distinguished triangle with a zero third vertex. -/
def K₀Subgroup : AddSubgroup (FreeAbelianGroup C) :=
  AddSubgroup.closure
    {x | ∃ (T : Pretriangulated.Triangle C), (T ∈ distTriang C) ∧
        x = FreeAbelianGroup.of T.obj₂ - FreeAbelianGroup.of T.obj₁ -
          FreeAbelianGroup.of T.obj₃}

/-- The Grothendieck group of a pretriangulated category `C`, defined as the quotient of
`FreeAbelianGroup C` by the distinguished triangle relations. -/
def K₀ : Type _ := FreeAbelianGroup C ⧸ K₀Subgroup C

/-- The `AddCommGroup` instance on `K₀ C`, inherited from the quotient. -/
instance K₀.instAddCommGroup : AddCommGroup (K₀ C) :=
  inferInstanceAs (AddCommGroup (FreeAbelianGroup C ⧸ K₀Subgroup C))

/-- The class map sending an object `X` of `C` to its class `[X]` in `K₀ C`. -/
def K₀.of (X : C) : K₀ C :=
  (QuotientAddGroup.mk (FreeAbelianGroup.of X) : FreeAbelianGroup C ⧸ K₀Subgroup C)

/-- For a distinguished triangle `T`, the class of `T.obj₂` equals the sum of the classes of
`T.obj₁` and `T.obj₃` in `K₀ C`. -/
lemma K₀.of_triangle (T : Pretriangulated.Triangle C) (hT : T ∈ distTriang C) :
    K₀.of C T.obj₂ = K₀.of C T.obj₁ + K₀.of C T.obj₃ := by
  simp only [K₀.of, K₀, ← QuotientAddGroup.mk_add]
  apply Quotient.sound
  change QuotientAddGroup.leftRel _ _ _
  rw [QuotientAddGroup.leftRel_apply]
  have h : FreeAbelianGroup.of T.obj₂ - FreeAbelianGroup.of T.obj₁ -
    FreeAbelianGroup.of T.obj₃ ∈ K₀Subgroup C :=
    AddSubgroup.subset_closure ⟨T, hT, rfl⟩
  convert (K₀Subgroup C).neg_mem h using 1
  abel

/-- The class of the explicit zero object vanishes in K₀. -/
lemma K₀.of_zero : K₀.of C (0 : C) = 0 := by
  have h := K₀.of_triangle C (Pretriangulated.contractibleTriangle (0 : C))
    (Pretriangulated.contractible_distinguished (0 : C))
  -- h : K₀.of C (contractibleTriangle 0).obj₂ = ... + K₀.of C (contractibleTriangle 0).obj₃
  -- contractibleTriangle 0 = Triangle.mk (𝟙 0) (0 : 0 ⟶ 0) 0
  -- obj₁ = obj₂ = 0, obj₃ = 0
  simp only [Pretriangulated.contractibleTriangle] at h
  -- h : K₀.of C 0 = K₀.of C 0 + K₀.of C 0
  have : K₀.of C (0 : C) + 0 = K₀.of C (0 : C) + K₀.of C (0 : C) := by
    rw [add_zero]; exact h
  exact (add_left_cancel this).symm

/-- Isomorphic objects have the same class in K₀. -/
lemma K₀.of_iso {X Y : C} (e : X ≅ Y) : K₀.of C X = K₀.of C Y := by
  have hdist := Pretriangulated.isomorphic_distinguished _
    (Pretriangulated.contractible_distinguished X)
    (Pretriangulated.Triangle.mk e.hom (0 : Y ⟶ (0 : C)) 0)
    (Pretriangulated.Triangle.isoMk
      (Pretriangulated.Triangle.mk e.hom (0 : Y ⟶ (0 : C)) 0)
      (Pretriangulated.contractibleTriangle X)
      (Iso.refl _) e.symm (Iso.refl _)
      (by simp [Pretriangulated.contractibleTriangle])
      (by simp [Pretriangulated.contractibleTriangle])
      (by simp [Pretriangulated.contractibleTriangle]))
  have h := K₀.of_triangle C _ hdist
  simp only [Pretriangulated.Triangle.mk] at h
  rw [K₀.of_zero, add_zero] at h
  exact h.symm

/-- The class of a zero object vanishes in K₀. -/
lemma K₀.of_isZero {X : C} (hX : IsZero X) : K₀.of C X = 0 := by
  rw [K₀.of_iso C (hX.iso (isZero_zero C)), K₀.of_zero]

variable {C} in
/-- A function `f : C → A` to an additive group is triangle-additive if
`f(B) = f(A) + f(C)` for every distinguished triangle `A → B → C → A⟦1⟧`. -/
class IsTriangleAdditive {A : Type*} [AddCommGroup A] (f : C → A) : Prop where
  additive : ∀ (T : Pretriangulated.Triangle C),
    T ∈ (distTriang C) → f T.obj₂ = f T.obj₁ + f T.obj₃

/-- The universal property of K₀: any triangle-additive function lifts
to an additive group homomorphism from K₀. -/
def K₀.lift {A : Type*} [AddCommGroup A] (f : C → A) [IsTriangleAdditive f] : K₀ C →+ A :=
  QuotientAddGroup.lift (K₀Subgroup C) (FreeAbelianGroup.lift f)
    ((AddSubgroup.closure_le _).mpr fun x ⟨T, hT, hx⟩ ↦ by
      simp only [SetLike.mem_coe, AddMonoidHom.mem_ker, hx, map_sub,
        FreeAbelianGroup.lift_apply_of]
      have h := IsTriangleAdditive.additive (f := f) T hT
      rw [h]; abel)

/-- The lift of a triangle-additive function agrees with the original function on generators. -/
@[simp]
lemma K₀.lift_of {A : Type*} [AddCommGroup A] (f : C → A) [IsTriangleAdditive f] (X : C) :
    K₀.lift C f (K₀.of C X) = f X :=
  FreeAbelianGroup.lift_apply_of f X

end CategoryTheory.Triangulated
