/-
Copyright (c) 2026 Mathlib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Formalization
-/
import Mathlib.CategoryTheory.Triangulated.Pretriangulated
import Mathlib.GroupTheory.FreeAbelianGroup
import Mathlib.GroupTheory.QuotientGroup.Defs

/-!
# Grothendieck Group of a Triangulated Category

We define the Grothendieck group `K₀ C` of a pretriangulated category `C` as the free abelian
group on objects of `C` modulo the distinguished triangle relations:
`[B] = [A] + [C]` for each distinguished triangle `A → B → C → A⟦1⟧`.

The isomorphism relation `[X] = [Y]` for `X ≅ Y` is derivable from the triangle relations
(via the distinguished triangle `X → Y → 0 → X⟦1⟧`), so we do not include it as a separate
generator.

## Main definitions

* `CategoryTheory.Triangulated.K₀Subgroup`: the subgroup of triangle relations
* `CategoryTheory.Triangulated.K₀`: the Grothendieck group with its `AddCommGroup` instance
* `CategoryTheory.Triangulated.K₀.of`: the class map `C → K₀ C`
* `CategoryTheory.Triangulated.K₀.of_triangle`: additivity on distinguished triangles
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits

universe v u

namespace CategoryTheory.Triangulated

variable (C : Type u) [Category.{v} C] [HasZeroObject C] [HasShift C ℤ]
  [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]

/-- The subgroup of `FreeAbelianGroup C` generated by the distinguished triangle relations:
`[T.obj₂] - [T.obj₁] - [T.obj₃]` for each distinguished triangle `T`.

The isomorphism relations `[X] - [Y]` for `X ≅ Y` are derivable, since any isomorphism
gives rise to a distinguished triangle with a zero third vertex. -/
def K₀Subgroup : AddSubgroup (FreeAbelianGroup C) :=
  AddSubgroup.closure
    {x | ∃ (T : Pretriangulated.Triangle C), (T ∈ distTriang C) ∧
        x = FreeAbelianGroup.of T.obj₂ - FreeAbelianGroup.of T.obj₁ -
          FreeAbelianGroup.of T.obj₃}

/-- The Grothendieck group of a pretriangulated category `C`, defined as the quotient of
`FreeAbelianGroup C` by the distinguished triangle relations. -/
def K₀ : Type _ := FreeAbelianGroup C ⧸ K₀Subgroup C

/-- The `AddCommGroup` instance on `K₀ C`, inherited from the quotient. -/
instance K₀.instAddCommGroup : AddCommGroup (K₀ C) :=
  inferInstanceAs (AddCommGroup (FreeAbelianGroup C ⧸ K₀Subgroup C))

/-- The class map sending an object `X` of `C` to its class `[X]` in `K₀ C`. -/
def K₀.of (X : C) : K₀ C :=
  (QuotientAddGroup.mk (FreeAbelianGroup.of X) : FreeAbelianGroup C ⧸ K₀Subgroup C)

/-- For a distinguished triangle `T`, the class of `T.obj₂` equals the sum of the classes of
`T.obj₁` and `T.obj₃` in `K₀ C`. -/
lemma K₀.of_triangle (T : Pretriangulated.Triangle C) (hT : T ∈ distTriang C) :
    K₀.of C T.obj₂ = K₀.of C T.obj₁ + K₀.of C T.obj₃ := by
  simp only [K₀.of, K₀, ← QuotientAddGroup.mk_add]
  apply Quotient.sound
  change QuotientAddGroup.leftRel _ _ _
  rw [QuotientAddGroup.leftRel_apply]
  have h : FreeAbelianGroup.of T.obj₂ - FreeAbelianGroup.of T.obj₁ -
    FreeAbelianGroup.of T.obj₃ ∈ K₀Subgroup C :=
    AddSubgroup.subset_closure ⟨T, hT, rfl⟩
  convert (K₀Subgroup C).neg_mem h using 1
  abel

end CategoryTheory.Triangulated
